# Generated by Django 5.1.2 on 2024-10-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_test_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
    ]
